spring:
  resources:
    static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/dtr-system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/  # 访问template下的html文件需要配置模板，映射
    cache: false  # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML
    encoding: UTF-8
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost   # Redis服务器地址
    port: 6379 # Redis服务器连接密码（默认为空）
    password: 123456 # Redis服务器连接密码（默认为空）
    max-active: 8  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1 #连接池最大连接数（使用负值表示没有限制）
    min-idle: 0  # 连接池中的最小空闲连接
    timeout: 300  # 连接超时时间（毫秒）
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB  # 单个上传文件的最大值
      max-request-size: 100MB  #  多个文件上传的最大值
mybatis:
  mapperLocations: classpath:mapper/*.xml  # Mapper 文件路径配置
logging:
  config: classpath:log4j2-spring.xml # 日志配置路径
server:
  port: 88  # 访问端口号